arch_betavae: True
loss_reconstruction: mse

residual_std: 1
gt_labels: True

factor_dim: 1
residual_dim: 8

train:
    batch_size: 128
    n_epochs: 20
    n_epochs_between_evals: 50
    n_epochs_between_visualizations: 10
    n_epochs_before_entropy: 20
    
    learning_rate:
        latent: 0.01
        classifier: 0.0001
        generator: 0.001
        min: 0.0001
    
    loss_weights:
        reconstruction: 1
        residual_decay: 0.00001
        
        entropy: 0.001
        classification: 0.001
        supervised: 10
